### ISSUE TITLE
additional dependency

### ISSUE THREAD

**Issue by onlykey** [trustcrypto/python-onlykey#1]
I set this up on Kali Rolling and the following additional steps where needed:

apt-get update
apt-get install python-pip
apt-get install cython 
apt-get install libudev-dev
apt-get install libusb-1.0-0-dev 
pip install hidapi
pip install aenum

Might want to add to documentation for dependencies for Debian Linux. Thanks again, having a command line tool like this will be very helpful.

**Comment by onlykey** [comment]
on Windows this also requires http://www.microsoft.com/en-us/download/details.aspx?id=44266

**Comment by onlykey** [comment]
on mac this error occurs during setup. 

Installed /private/tmp/easy_install-4We4Oj/hidapi-0.7.99.post18/Cython-0.24.1-py2.7-macosx-10.11-intel.egg
error: Setup script exited with error: unknown file type '.pxd' (from 'chid.pxd')

Still looking for resolution

**Comment by onlykey** [comment]
@tsileo I got it working on Mac. See above. Question - why do the hex bytes have some weird characters (Shown in bold above)?

**Comment by tsileo** [comment]
Awesome you got it working on Mac!
First things I do on a Mac is installing brew and replacing the system Python. That's why I had nothing to do to install hidapi.
Python sucks for distributing package/cli when you don't have a dev environment.
But thanks to your notes, I'll update the README so it'll be easy for people.

I may try to write a another CLI/package in golang. So we'll just have to upload the compiled binary on GitHub as a release.

For you Windows issue (I don't have any computer running Windows at home :-), try installing six:

```
$ pip install six
```
And about the weird hex bytes, it's the way Python represent string (weird I know), if the byte represent a displayable character in the ASCII table it'll display it.

```
>>> ord('A')
65
>>> chr(65)
'A'
>>> '\x41'
'A'
```

Let me know if you have any other question!

**Comment by onlykey** [comment]
@tsileo Thanks yes I will try Windows again later but as long as Mac works I am good for now. I did run into an issue I was wondering if you would help me with. I compiled the firmware getting ready to test the release candidate and found that with serial off (We turn this off for production firmware) the SSH test is not working. This could be because now the order of the USB devices has changed. Instead of having 3 devices - Serial, RAWHID, Keyboard now there is only 2 RAWHID, Keyboard. Or if the python script is relying on the serial messages that would do it to. Here is the output with the same firmware, first output is with Debug on, 2nd is with Debug off.

Ts-MacBook-Pro:tests t$ python ssh_auth.py 
Generating a new ed25519 key pair...
Done

privkey= '+p\xca$\xa4\xae\xf6:\xfb\xab\xfc\x13p\x85\xb3{\x9ft\x0f{i(j\xa0XW\x1b\xa8\x12(j\xc8'
privkey hex= 2b70ca24a4aef63afbabfc137085b37b9f740f7b69286aa058571ba812286ac8
pubkey= '\xe2Q\x98\xf9\x9d\x0e\xa5\x06\xd1\xd5\xb5c(\xc2e/IO/\x1bz\xc7`m\xb5[\xfa-J\xed\xa3\xfd'
pubkey hex= e25198f99d0ea506d1d5b56328c2652f494f2f1b7ac7606db55bfa2d4aeda3fd


Initialize OnlyKey client...
No handlers could be found for logger "onlykey.client"
Done

You should see your OnlyKey blink 3 times

Setting SSH private...
Successfully set SSH private key
You should see your OnlyKey blink 3 times

Trying to read the pubkey...

Assert that the received pubkey match the one generated locally
Ok

test_payload= '=H\xee\x89Il\x7f\xb0\x1f\x13\\*0\xde\xcf\x03`\x87q\xd4\x19+*}\xc3W\xaa\xf3\xc2\xdb\xe4\x7f\x1cn,o,\x9d>B/j\xad*W\xb3c\xae\x84\xd2[\xb1-\x1c\xe3p\xf0<^\xc0\xdd\x83\x92P\xee&\xb6k\xe5\xe1!\xa7\xf01\xd9\xfb\xf7\xf6N.7\x8fE\xcbE3\xb2[\x8a\x87\x07\xdd\xa6N\t\xcc\x0cHG\xa3\xba\xa0\xee\x7f\xcbM-T\xc8\x0bD\xe0\x88\x9b\x18\xcf.\xbdv\xf51(\xe9\x8du\x02\x8eW\x1aP\xc6\x08C\x9a\x07\x96B\xf13\xc1\x13I3W&\x02\x850\x03\xe0'

Sending the payload to the OnlyKey...
Please touch a button (and press ENTER if necessary)

Signed, signature= '^~\x9e\xe8K\xe0zx#Q\x11\xe0\x19\xf7\xa3\xe2\xb1\x19\xae\xfe\xd0\x823\t\n\xf2\xea\xf8\xb5\xf1W\x030\x93\xf1\x00\xc8n\xb9\xb9\x9cH\x8ap\x8a\x92\x97U\xaa\xb5ws\x0cfP|\x975\xd3\x80\x92\xaf\xa4\x06'
Local signature= '^~\x9e\xe8K\xe0zx#Q\x11\xe0\x19\xf7\xa3\xe2\xb1\x19\xae\xfe\xd0\x823\t\n\xf2\xea\xf8\xb5\xf1W\x030\x93\xf1\x00\xc8n\xb9\xb9\x9cH\x8ap\x8a\x92\x97U\xaa\xb5ws\x0cfP|\x975\xd3\x80\x92\xaf\xa4\x06'
Assert that the signature generated locally match the one generated on the OnlyKey
Ok

Done
Ts-MacBook-Pro:tests t$ python ssh_auth.py 
Generating a new ed25519 key pair...
Done

privkey= 'U\x97\xb1\xe6\x04\xe1\xf5\xb2l\xd1fg\x00\xd1\xb7/\x95\\!1\xa3\xbc8~\x82\x89<;\xc7m\xf8\x1f'
privkey hex= 5597b1e604e1f5b26cd1666700d1b72f955c2131a3bc387e82893c3bc76df81f
pubkey= '\xc4\x1b\xfe\x9d\xefLr\x9fU\xd0B>\xc1\xf9\x08r\xdct\xcf\x9c\xab\x18RH2\x13\xb6r\xce0\x18\x16'
pubkey hex= c41bfe9def4c729f55d0423ec1f90872dc74cf9cab1852483213b672ce301816


Initialize OnlyKey client...
No handlers could be found for logger "onlykey.client"
Traceback (most recent call last):
  File "ssh_auth.py", line 22, in <module>
    ok = OnlyKey()
  File "build/bdist.macosx-10.11-x86_64/egg/onlykey/client.py", line 98, in __init__
onlykey.client.OnlyKeyUnavailableException

I would appreciate any help you can provide. If you want to compile without Debug let me know there are additional steps required. Here is a pre-compiled hex with debug off - https://github.com/trustcrypto/OnlyKey-Firmware/tree/master/OnlyKey_Beta/US%20Firmware

**Comment by tsileo** [comment]
Sure, let me take a look.

**Comment by tsileo** [comment]
I already tried the Python client with Serial off and it was working. But I haven't tested the SSH feature with debug off.

**Comment by tsileo** [comment]
I updated the repo, I increased the timeout, the script runs on my Mac, you should try multiple times it should work.

But then there's another issue, it doesn't return the good pubkey anymore:

```
Generating a new ed25519 key pair...
Done

privkey= "\xb3N'\xee>P\xa5\x8fC'\xad\xa3\xc6\xffJz\xbf\xb5_\xed\xd5s\xc8\x00\x86V\xce=\xd3\x9e9["
privkey hex= b34e27ee3e50a58f4327ada3c6ff4a7abfb55fedd573c8008656ce3dd39e395b
pubkey= '%\x9a\xe6\xafx\xbe\x88K\x8f\xd0\xdf\xb6A\x9a\xbb\xb8\x94\xf8p\xd2\x86\xc7\xbf\xf9\x17j\xe5\xe2<K+\xff'
pubkey hex= 259ae6af78be884b8fd0dfb6419abbb894f870d286c7bff9176ae5e23c4b2bff


Initialize OnlyKey client...
Done

You should see your OnlyKey blink 3 times

Setting SSH private...
Successfully set SSH private key
You should see your OnlyKey blink 3 times

Trying to read the pubkey...

received= 'o\x08\x9e\xfe\x89\x08Re\xe0{V\x8cy\xa9l\x11\xccAQ\xab.\x17\x18\x0by\x86Y\xc8\xe2D\xa9\xa9'
Assert that the received pubkey match the one generated locally
Traceback (most recent call last):
  File "tests/ssh_auth.py", line 62, in <module>
    assert ok_pubkey == pubkey.to_bytes()
AssertionError
```

**Comment by tsileo** [comment]
I got it! making a PR.

**Comment by tsileo** [comment]
PR sent on the libraries repo.

**Comment by tsileo** [comment]
And just to clarify, I got it working with the new firmware you sent me, the few first run it did not work I don't know why. but then it worked except the test failed halfway because the pubkey wasn't good.

The issue was the offset of the buffer was not set correctly due to the debug ifdef, it also affected U2F. That's the PR I sent on trustcrypto/libraries.
