### ISSUE TITLE
ssh_test on mac

### ISSUE THREAD

**Issue by onlykey** [trustcrypto/python-onlykey#2]
So I did have the ssh_test working on mac but now no luck. I tried increasing the delays in ssh_auth.py thinking it might be a timing issue and added debug messages to firmware so I can make sure the public keys match but I am still getting this error any ideas?

received= '\xeept\xbbQf\xe7\xe1\xfb3;\xfa=\xc8\xa3\xac\x93\x1e2@X\xe0\xdf&\x1c\xfej\x01\x1e\xe94\x11'
> /Users/t/Documents/python-onlykey/tests/ssh_auth.py(59)<module>()
-> if not ok_pubkey:
(Pdb) 

![image](https://cloud.githubusercontent.com/assets/18121756/18732843/3a86b8bc-8034-11e6-94cc-2509a18024d9.png)

**Comment by onlykey** [comment]
@tsileo Just wondering if this is still working for you since nothing has really changed in the firmware. Trying to troubleshoot if something has changed on the Mac.

**Comment by tsileo** [comment]
Hi Tim, I'm sorry for the long delay. The script is still working well, PDB is the Python DeBugger and I left a debug call by mistake. I pushed the fix it should works now.

I only affected the test script, not the CLI/Python lib.

Let me know if you still have issues and sorry again.
