### ISSUE TITLE
cannot use onlykey-cli to set slot 4b or higher

### ISSUE THREAD

**Issue by schnook** [trustcrypto/python-onlykey#26]
Issue appears to be in:
https://github.com/trustcrypto/python-onlykey/blob/master/onlykey/client.py
`        if slot_number >= 10:`
`            slot_number += 6`

If I change the first line to: `if slot_number >= 13:` everything seems to work, but I don't know what I have broke in the process.

**Comment by onlykey** [comment]
@schnook I just pushed a fix for this. This should just be removed it was for support of an older version of firmware. Thanks for testing it.
