### ISSUE TITLE
Port to Python 3

### ISSUE THREAD

**Issue by scj643** [trustcrypto/python-onlykey#29]
This code should be ported to Python 3 due to Python 2 EOL in 2020.

**Comment by c0d3d** [comment]
Better late then never, see #31 haha

**Comment by michaelblyons** [comment]
#31 is merged. Close this issue?

**Comment by haplo** [comment]
I think `read_bytes` is broken, please see my fix in #35.

**Comment by haplo** [comment]
Also I think the README should be updated to highlight that Python 2.7 is now deprecated and unsupported, and instruct people to use `pip` and `pip3`, not `pip2`.

**Comment by onlykey** [comment]
@haplo The version on pypi is still python 2 but yes once this is released that will be updated. As of right now there is no released python3 version. The agent has been updated for python 3 and GPG support here - https://github.com/onlykey/trezor-agent/tree/onlykey-agent-merge

**Comment by haplo** [comment]
@onlykey Thanks for the link, I will give that branch of *trezor-agent* a try when I have time.
