### ISSUE TITLE
Labels not get displayed correctly

### ISSUE THREAD

**Issue by bryanpedini** [trustcrypto/python-onlykey#66]
It seems that sometimes the labels do not get displayed correctly.
I observed the following behavior after immediately restoring a backup I just finished performing (I was doing some tests with FIDO PIN and stuff via CLI):
![Screenshot_20220716_165426](https://user-images.githubusercontent.com/45012292/179360378-7e03fe89-138b-4aad-ac39-c9d8d72265b3.png)

Perhaps the app is expecting the labels to start at byte X of return messages while the key outputs the labels starting at byte Y?

Related:
https://github.com/trustcrypto/OnlyKey-Firmware/issues/149
https://github.com/trustcrypto/OnlyKey-App/issues/201
(either there's an issue with both the app and the CLI (or the app underlying uses the CLI), or there's something in the firmware... tho I'm not qualified nor expert enough to determine. Feel free to close the issues where they're not relevant)

**Comment by onlykey** [comment]
@bryanpedini What version of the app are you using? There were some label display issues in 5.3.5 but there have been no other reported issues in 5.3.6

**Comment by bryanpedini** [comment]
On the desktop where I experienced this, app v5.3.6 and CLI v1.2.9.
Tho I noticed now that the CLI has another issue when viewing the version:
```
$ onlykey-cli version
OnlyKey CLI v1.2.9
Exception ignored in atexit callback: <function exit_handler at 0x7fc89d1495a0>
Traceback (most recent call last):
  File "/home/bryanpedini/.local/lib/python3.10/site-packages/onlykey/cli.py", line 1204, in exit_handler
    only_key._hid.close()
AttributeError: 'OnlyKey' object has no attribute '_hid'
```

**Comment by onlykey** [comment]
@bryanpedini I wasn't able to reproduce the version command issue. There is a newer version of the CLI now v1.2.10

**Comment by bryanpedini** [comment]
> There is a newer version of the CLI now v1.2.10

Thanks for the info, I upgraded with `pip install --upgrade onlykey` but some error persist. To be noted, I'm on Arch Linux so I might have different underlying packages, I could try on a Docker container with some standard (fixed) distribution instead of a rolling release.
Let me know how I can help debug:
![Screenshot_20220725_083740](https://user-images.githubusercontent.com/45012292/180713847-2d80ea57-813b-4502-96b9-8d5c1d21c877.png)

Also, `getlabels` works perfectly fine unless there is some strange condition, I managed to get some Python error performing some short-timed and consecutive `getlabels` but I was not able to reproduce the issue once I disconnected the OnlyKey and I reconnected it and typed my primary PIN... so now it works perfectly fine *every  time* (?) who knows ¯\_(ツ)_/¯
